### ISSUE TITLE
Internal error when trying to save floor pattern

### ISSUE THREAD

**Issue by star-kissed** [Leon167/BlockParty#18]
![Screen Shot 2020-03-26 at 1 33 24 AM](https://user-images.githubusercontent.com/61160157/77622279-985c6b00-6f03-11ea-9811-b59e98a07bf6.png)

When I try to save a floor plan it says there was an internal error and this shows up in console. I'm not sure how to fix this.

**Comment by Leon167** [comment]
Thank you for letting me know. Fixed it. The Fix will be available in the next release
