### ISSUE TITLE
FEATURE IDEA: Execute command per player if game ends

### ISSUE THREAD

**Issue by Headpijn** [Leon167/BlockParty#19]
Hey! I have a quick question. 
Is is possible, to execute a command if the game ends? Per example, if I win the game, my reward is the command: /nl givexp 10
and the players who lost: /nl givexp 5.
because I'm using the leveling plugin, NetworkLevels, I want the players to get higher level if they play the game.

If this is not possible, would u mind adding this feature (adding/executing commands on win)? 
Thanks in advance!

**Comment by Leon167** [comment]
Sure, i'll add this in the next release.

**Comment by Headpijn** [comment]
Thank u very much! Can u maybe estimate when the next release will be public?

Thanks in advance!

**Comment by Leon167** [comment]
Testing takes a lot of time. I can publish an alpha build, but it's only going to be available on GitHub. Probably need 1-2 days for the first alpha release and one week to release the 'release' build

**Comment by Headpijn** [comment]
Ah oke, understood! Again, thank u very much!
