### ISSUE TITLE
Unable to start block party 

### ISSUE THREAD

**Issue by star-kissed** [Leon167/BlockParty#20]
When I run the command /bp start arena1 it says “Arena “start” doesn’t exist”

**Comment by Headpijn** [comment]
Same issue ^^

**Comment by Headpijn** [comment]
Maybe u can share a screenshot of your console, that makes it easier for the developer to find the issue I guess

**Comment by pauhull** [comment]
Should be fixed now. Please check if the problems still occurs with the attached version of the plugin

[BlockParty-2.0.3.5-ALPHA.zip](https://github.com/Leon167/BlockParty/files/4390184/BlockParty-2.0.3.5-ALPHA.zip)

**Comment by star-kissed** [comment]
![Screen Shot 2020-03-26 at 4 37 52 PM](https://user-images.githubusercontent.com/61160157/77703461-794fee80-6f80-11ea-8b0a-5db07840f466.png)
Internal error when I use /bp start arena1 and says "couldn't find command" when I use /bp savepattern

**Comment by Leon167** [comment]
Should work now: https://github.com/Leon167/BlockParty/releases/tag/v2.0.3.5-ALPHA

**Comment by pauhull** [comment]
Addressing your second problem, there is no command called "/bp savepattern". Perhaps you meant "/bp createpattern"

**Comment by star-kissed** [comment]
Yes that’s what I meant

**Comment by star-kissed** [comment]
/bp createpattern is fixed but I still get an internal error when I use /bp start arena1

**Comment by pauhull** [comment]
Bug is now fixed & tested.


[BlockParty-2.0.3.5-ALPHA.zip](https://github.com/Leon167/BlockParty/files/4394524/BlockParty-2.0.3.5-ALPHA.zip)

**Comment by star-kissed** [comment]
Says unknown command

**Comment by pauhull** [comment]
Please show your console output

**Comment by star-kissed** [comment]
![Screen Shot 2020-03-27 at 11 21 26 AM](https://user-images.githubusercontent.com/61160157/77782688-49a2f400-701d-11ea-9e35-3b9fc1355aa5.png)
Now says internal error

**Comment by star-kissed** [comment]
Ok I figured it out, you have to type /bp start arena arena1. However how many people are suppose to be in to start it? It says “game start aborted because there are not enough players”. I have 9 people on rn. Is there a way to change the number in config?
